[default.extend-words]
"Anythin" = "Anythin"
"Assumin" = "Assumin"
"Drawin" = "Drawin"
"Everythin" = "Everythin"
"Livin" = "Livin"
"PN" = "PN"
"Wha" = "Wha"
"anythin" = "anythin"
"chasin" = "chasin"
"comparin" = "comparin"
"dancin" = "dancin"
"doin" = "doin"
"durin" = "durin"
"everythin" = "everythin"
"fillin" = "fillin"
"filterin" = "filterin"
"gettin" = "gettin"
"givin" = "givin"
"goin" = "goin"
"guardin" = "guardin"
"havin" = "havin"
"hikin" = "hikin"
"jus" = "jus"
"klicks" = "klicks"
"learnin" = "learnin"
"leavin" = "leavin"
"lieve" = "lieve"
"lookin" = "lookin"
"lyin" = "lyin"
"makin" = "makin"
"mappin" = "mappin"
"missin" = "missin"
"mornin" = "mornin"
"nothin" = "nothin"
"otherways" = "otherways"
"practic" = "practic"
"runnin" = "runnin"
"settin" = "settin"
"shoppin" = "shoppin"
"sittin" = "sittin"
"somethin" = "somethin"
"startin" = "startin"
"takin" = "takin"
"tryin" = "tryin"
"tyin" = "tyin"
"usin" = "usin"
"wha" = "wha"
"workin" = "workin"
"wou" = "wou"
