[default.extend-words]
"Doin" = "Doin"
"Runnin" = "Runnin"
"anythin" = "anythin"
"doin" = "doin"
"drawin" = "drawin"
"everythin" = "everythin"
"figurin" = "figurin"
"gettin" = "gettin"
"goin" = "goin"
"havin" = "havin"
"lookin" = "lookin"
"makin" = "makin"
"nothin" = "nothin"
"rechargin" = "rechargin"
"settin" = "settin"
"somethin" = "somethin"
"tryin" = "tryin"
