---
title: select
---
flowchart LR
  A[select]
  B(chooses)
  C[rows]
  D[columns]
  E(specified by)
  F[names]
  G[calculations]
  H[for all]
  I(from)
  J[table]
  K(identified by)
  L[name]
  M(can be paged with)
  N(can be filtered by)
  O[limit]
  P[offset]
  Q[condition]
  R(evaluated for each)
  S(must be)
  T[Boolean]
  A --> B
  B --> C
  B --> D
  D --> E
  E --> F
  E --> G
  E --> H
  D --> I
  C --> I
  I --> J
  J --> K
  K --> L
  C --> M
  C --> N
  M --> O
  M --> P
  N --> Q
  Q --> R
  R --> C
  Q --> S
  S --> T
