[default.extend-words]
"Mornin" = "Mornin"
"anythin" = "anythin"
"everythin" = "everythin"
"gettin" = "gettin"
"kidnappin" = "kidnappin"
"missin" = "missin"
"passin" = "passin"
"somethin" = "somethin"
